### ISSUE TITLE
Script not functioning at all

### ISSUE THREAD

**Issue by thomasrussellmurphy** [hubot-scripts/hubot-google-translate#3]
IRC interface gives no response to a `hubot translate me` command. Direct invocation of the hubot console results in all translation requests returning `undefined!`.

The command shows up in `help`, so I know I at least have the script installed, but I'm not sure what might be messed up. I'm currently working on updating the hubot instance I help run at https://github.com/thomasrussellmurphy/lulu/tree/fix-translate

**Comment by vladh** [comment]
I have this problem as well

**Comment by technicalpickles** [comment]
Somehow I wasn't watching this repo. Sorry for the hassle!

@sija started https://github.com/hubot-scripts/hubot-google-translate/issues/4 to fix... @thomasrussellmurphy and @vladh , would you mind trying that out and seeing if it fixes the issue?

**Comment by thomasrussellmurphy** [comment]
@technicalpickles took a look and commented on the PR. That fix appears to work.

**Comment by bevacqua** [comment]
Everyone see: https://github.com/bevacqua/hubot-yandex-translate

**Comment by juanbrujo** [comment]
https://github.com/hubot-scripts/hubot-google-translate/pull/4 fixes, please consider merging it.

**Comment by dylanh724** [comment]
6/4 still not working, any update to this? Identical - shows up in help, but doesn't respond at all in hipchat.

**Comment by thomasrussellmurphy** [comment]
We're still waiting on the fix to be merged.

**Comment by dylanh724** [comment]
(Yandex translate works btw -- but you have to edit out the "HODOR hodor"
for every response in the main js file :P)
